<%@ Page Title="" Language="C#" MasterPageFile="~/App/Site1.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="GanaderiaWeb.Default" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
   
   <style type="text/css">#nycntg{margin:6px 25px 10px 0}#nycp{background-color:#fafafa;border-left:1px solid #ebebeb;bottom:0;left:0;margin-left:33px;min-width:240px;position:absolute;right:0;top:0;visibility:hidden;z-index:102;padding:38px 16px 10px 31px}.nyc_open #nycp{visibility:visible}#nycf{display:none;height:1px;left:0;min-width:940px;position:absolute;visibility:hidden;z-index:-1}.nyc_open #nycf{display:block}.nyc_opening #nycp,.nyc_opening #nycprv{display:block;visibility:hidden!important}#nyccur{background:#fafafa;height:100%;left:33px;opacity:0;position:absolute;top:0;width:0;z-index:120}#nyccur.wipeRight{border-right:1px solid #e8e8e8;opacity:1;-webkit-transition:width 0.08s ease-in;width:100%}#nyccur.fadeOut{opacity:0;-webkit-transition:opacity 0.08s linear;width:100%}#nyccur.fadeIn{opacity:1;-webkit-transition:opacity 0.08s linear;width:100%}#nyccur.wipeLeft{border-right:1px solid #eee;opacity:1;-webkit-transition:width 0.08s ease-out;width:0}.nyc_open .vspib,.nyc_opening .vspib{padding-right:0;-webkit-transition:padding-right .2s ease}.nyc_open .vspib .vspii,.nyc_opening .vspib .vspii{-webkit-border-top-right-radius:0;-webkit-border-bottom-right-radius:0;border-right:none}.nyc_open #nycxh{cursor:pointer;opacity:0.7;padding:15px;position:absolute;right:1px;top:12px}.nyc_open #nycxh:hover{opacity:1}#nycx{display:none}.nyc_open #nycx{border:none;cursor:pointer;display:block;padding:0}#nycntg h3 .esw{display:none}#nyc .vshid{display:inline}#nyc #nycntg .vshid a{white-space:nowrap}#nycntg a:link{border:0;text-decoration:none}#nycntg a:hover{text-decoration:underline}#vsi,.vsi{border:none;width:100%}.vslru.vso:before{bottom:-8px;top:-7px;left:-7px;right:-9px;content:"";position:absolute;z-index:-1}.vslru div.vspib{bottom:-6px;top:-7px}.vslru div.vspib .vspii{border-radius:0}.vscl.vso.vslru:before,.vscl.vslru div.vspib{top:-4px}</style>

     <h1>UNITECBIO: GANADERO </h1>
</asp:Content>
